### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AhmetCanSolak**

### CODE REVIEW

**Comment by keithchev** [comment]
I think we need to check with Pete before making any changes to the README. And for clarity I would suggest adding the image file for the new logo directly to the repo.

**Review by rafa-gomez-s — CHANGES_REQUESTED** [review]
Until further notice, we should not say the org is the Network, we should actually specify that it's still the SF Biohub that owns the org account.
So, keep the original text, but update the logo, and change the link to https://czbiohub.org/sf, and the name of the organization to "The Chan Zuckerberg Biohub San Francisco".

We should make the changes you suggest only after we are told that the Github org account should migrate to the Network.

Thank you!

**Comment by AhmetCanSolak** [comment]
Addressed your comments @rafa-gomez-s , please give it a look again when you get a chance.

**Review by rafa-gomez-s — APPROVED** [review]
This is perfect, and I don't think we need Pete to approve. The logo is now official everywhere, and it's totally reasonable to make it clear that the Github Org is only for the SF Biohub.

**Comment by keithchev** [comment]
Agreed; I think we only need to go to Pete for substantive changes to the readme.

**Review by keithchev — APPROVED** [review]

**Comment by AhmetCanSolak** [comment]
Thank you both!

**Pull request merged**
